name = "human-activity-ml-julia"
author = ["Thomas Zub <thomas.zub@outlook.de>"]
version = "0.1.0"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"
